### ISSUE TITLE
Rails compatible file

### ISSUE THREAD

**Issue by bradrobertson** [nickjj/manifest-revision-webpack-plugin#1]
Just throwing this idea out there. Would it be possible to have a configurable format for this manifest? Or, since it's 50% of the way there, how would you feel about adding a 'files' section that would make this compatible with the (Rails Asset Pipeline Manifest format](http://guides.rubyonrails.org/asset_pipeline.html#precompiling-assets) (scroll down a bit).

I'm trying to fully replace the crappy rails asset pipeline, but I'd still like all their great view helpers to work out of the box. This plugin is SO CLOSE to achieving that for me, it's just missing the `files` section from the manifest.

Thoughts?

**Comment by nickjj** [comment]
Where does the `files` section need to be placed, at the root of the json file? Example:

Old:
```
{
    // Everything else goes here as is.
}
```

New:
```
files: {
    // Everything else goes here as is.
}
```

---

I wouldn't be opposed to making that change. It could be exposed with a `manifestPrefixNode` option that defaults to `null`. Would that change alone make it work flawlessly with the Rails asset pipeline?

**Comment by bradrobertson** [comment]
ya it's on the root, same as the `assets` key. Looks like this:

```json
{
  "files": {
     "application-723d1be6cc741a3aabb1cec24276d681.js": {
        "logical_path":"application.js",
        "mtime":"2013-07-26T22:55:03-07:00",
        "size":302506,
        "digest":"723d1be6cc741a3aabb1cec24276d681"
     }
  },
  "assets": {
    "application.js": "application-723d1be6cc741a3aabb1cec24276d681.js"
  }
}
```

That'd be amazing if you could add something like that. I'm *pretty* sure that would make it work seamlessly with Rails. We're in the process of building out a new Rails app with webpack so I'd be happy to test it out for you.

**Comment by nickjj** [comment]
In the example you provided the `assets` field is still hanging off the root, it's not inside of `files`. Are you saying rails needs both fields?

I wonder if it'll work without the mtime, size and digest too.

**Comment by bradrobertson** [comment]
ya it's on the root. NOT inside of files. It uses 2 keys for all the assets `files` and `assets`. I don't know exactly what the rest of the info is used but, but I'd imagine mtime/size are not requirements. 

I don't completely know *why* the format is the way it is (ie what size/digest are used for) so it might take some experimentation.

I'll try to sift through the rails asset pipeline source tomorrow to figure out a bit more so I can comment further.

**Comment by bradrobertson** [comment]
It *looks* at a glance, for the view helpers to work that load up the assets that just `logical_path` is needed (under the `files` entries). I'm assuming the rest is for re-compilation purposes (for optimizations). So I'm guessing we could get away with this format:

```json
{
  "files": {
     "application-723d1be6cc741a3aabb1cec24276d681.js": {
        "logical_path":"application.js"
     }
  },
  "assets": {
    "application.js": "application-723d1be6cc741a3aabb1cec24276d681.js"
  }
}
```

Don't ask me *why* they use this format, it just seems superfluous to me.

**Comment by nickjj** [comment]
Ok, that's an annoying format because it's so different than what's currently there. The bright side is there's nothing there that'll cause complications, I have all of those property values accounted for.

Maybe we need a `railsAssetPipelineMode` boolean option and when true it uses the format you proposed. What do you think?

**Comment by bradrobertson** [comment]
Ya I think that'd be great. Another option which might allow for more flexibility in the future would just be to have a `format` option (string value), which defaults to yours, but could have a `rails` format as well?

Something like this for instance?
```javascript
new ManifestRevisionPlugin("manifest.json", {
  format: "rails" // defaults to "default"
});
```

I think either way is fine. Right now if you just added in the `files` section to the root of the manifest, I'm pretty sure it would work, but I don't know if that conflicts with your original format. It also adds a lot of bloat to your manifest if it's not something you actually need, so maybe having different format options is best.

I'm happy to contribute here but I'm *extremely* new to Webpack plugins (having never written one) and I've found the docs less than helpful.

**Comment by nickjj** [comment]
I like the format option. This is my first webpack plugin too, I pretty much just looked around at other plugins, you're right in that the docs are a bit light.

I have a Flask extension written to use this plugin in my webpack setup. I'm going to be tweaking and publishing that package in the next few days. I'll work in the formatter here around that time.

**Comment by bradrobertson** [comment]
That's great! Let me know if there's anything I can help with.

**Comment by nickjj** [comment]
@bradrobertson One last question. In the assets section, you have `application.js` as the key. Does this need to be just the file name or does it need the logical path? The examples in the docs all have no extra path associated to the file.

Maybe you can just paste in an example manifest file from one of your projects here?

**Comment by bradrobertson** [comment]
It would need to be the full path relative to where it's being compiled into. So if I'm compiling files into subdirectories, it should contain those. Here's an example:

```json
{
  "files": {
    "css/community-ede15526.css": {
      "logical_path": "css/community.css",
      "mtime": "2015-05-27T13:11:47.000Z",
      "size": 136355,
      "digest": "ede15526"
    },
    "js/bundle-b602605e.js": {
      "logical_path": "js/bundle.js",
      "mtime": "2015-05-27T13:12:18.000Z",
      "size": 743617,
      "digest": "b602605e"
    }
  },
  "assets": {
    "css/community.css": "css/community-ede15526.css",
    "js/bundle.js": "js/bundle-b602605e.js"
  }
}
```

Note this is how we're doing it in gulp currently, hence the css. I believe webpack actually compiles the css into the js files, but this just illustrates the nested structure. I'd include these assets using a rails helper that looks like this:

```erb
<%= javascript_include_tag('js/bundle.js') %>
```

**Comment by nickjj** [comment]
Ok great, that's what I'm doing in Flask too. Expect a new version to be pushed sometime later today.

**Comment by nickjj** [comment]
Can you test what's on master against your project? The readme is updated for the new options available.

**Comment by bradrobertson** [comment]
Works :)

See [here](http://rabbit.delete-me.c66.me) and the manifest it's using [here](http://rabbit.delete-me.c66.me/assets/manifest.json)

**Comment by nickjj** [comment]
Awesome, can you create a wiki page walking through how you set up rails to use this plugin?
