### ISSUE TITLE
No possibility to ignore exact files

### ISSUE THREAD

**Issue by boccob** [nickjj/manifest-revision-webpack-plugin#14]
I would like to have a possibility to ignore not only file catalog path but full path to the file.
For example, I could have `.DS_Store` in some folder and I would like to ignore it.

It could be easily done with an update of `walkAndPrefetchAssets` function. I could make PR if you think that it's a good idea.

**Comment by nickjj** [comment]
Sure, that sounds like a good idea. Go for it.

However I think if we go down this path maybe it support pattern matching too? This way you could say "ignore all dotfiles", or whatever you want.

Perhaps the option could take a list of file names?

**Comment by boccob** [comment]
@nickjj It's still the same `ignorePaths` with regexp support. But now it takes into account file name as well (not only path as it was before).

**Comment by boccob** [comment]
@nickjj well, `ignorePaths` does not support regexp. I mixed up this with another webpack config property (so much inconsistencies!).
I added regexp support and updated readme.
