### ISSUE TITLE
Calling other formatters

### ISSUE THREAD

**Issue by REBELinBLUE** [nickjj/manifest-revision-webpack-plugin#22]
Hi,

Sorry if this is really obvious but is there a way to all other formatters for a custom formatter? Basically I am looking at formatting the manifest for Laravel elixir (which I believe uses gulp-rev) and it is almost exactly the same as the "general" formatter, just that instead of

```json
{
    "assets": {
        "file.js": "file.hash.js"
    }
}
```

it is simply

```json
{
    "file.js": "file.hash.js"
}
```

i.e. the "assets" key is the top level.

So it seems that really my custom formatter just needs to call the general formatter and then just return the assets key

**Comment by REBELinBLUE** [comment]
Sorry, I'm an idiot. Literally as soon as I asked I realised

```js
const Formatter = require('manifest-revision-webpack-plugin/format');
const elixirFormatter = function (data, parsedAssets) {
  const format = new Formatter(data, parsedAssets);
  const outputData = format.general();

  return outputData.assets;
};
```

**Comment by nickjj** [comment]
No worries. If you want to open a PR (along with a test and proper documentation updates), I'll accept it so that there's built in support for Laravel.

**Comment by REBELinBLUE** [comment]
👍 I'll see if I have time this evening :)
