### ISSUE TITLE
Question: correct use case

### ISSUE THREAD

**Issue by vladra** [nickjj/manifest-revision-webpack-plugin#26]
Hi!

I'm struggled a bit with correct use case. If I understood correctly, `rootAssetPath` points to the folder where webpack will output all files. But this produces several errors for me:

```
ERROR in ./public/bundle.min.js.map
Module parse failed: **************/app/public/bundle.min.js.map Unexpected token (1:10)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:10)
```
```
ERROR in ./public/assets.json
Module parse failed: **************/app/public/assets.json Unexpected token (1:9)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:9)
```
```
ERROR in ./public/.gitkeep
Module parse failed: **************/app/public/.gitkeep Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '#' (1:0)
```

Adding webpack loaders to cover those files seems weird to me. So I was thinking that I'm doing something wrong. Any tips?

Thanks in advance

**Comment by nickjj** [comment]
Hi,

This is related to https://github.com/nickjj/manifest-revision-webpack-plugin/issues/25.

**Comment by vladra** [comment]
It seems so. I could blacklist json or git file, but I stil need to process map file.

Didnt find proper way to do this with plugin. Did manifest using ruby.
