### ISSUE TITLE
Edit asset manifest json from options 

### ISSUE THREAD

**Issue by lgordey** [nickjj/manifest-revision-webpack-plugin#3]
Hi!

Can u add an option to make access to edit output asset json?

Now i have in manifest such asset object as:
```javascript
"assets": {
    "images/hamburger.svg": "images/hamburger.d2cb0dda3e8313b990e8dcf5e25d2d0f.svg",
    "images/spinner.gif": "images/spinner.37348967baeae34bfa408c1f16794db1.gif",
}
```

But i want to have:
```javascript
"assets": {
    "hamburger.svg": "images/hamburger.d2cb0dda3e8313b990e8dcf5e25d2d0f.svg",
    "spinner.gif": "images/spinner.37348967baeae34bfa408c1f16794db1.gif",
}
```
So I can describe it as:
`filename(key): outpath_to_file`

For example:
```javascript
new Manifest(path.join(_path + '/config', 'manifest.json'), {
     rootAssetPath: rootAssetPath,
     ignorePaths: ['/stylesheets', '/javascript'],
     keyWithPath: false // default true to show with path
}),
```

Thanks!

**Comment by nickjj** [comment]
You can build your own custom `manifest.json` file already.

Check out:
https://github.com/nickjj/manifest-revision-webpack-plugin#api

You can pass in your own formatter and have it output the file however you want. It gives you access to all the data necessary to do what you're requesting.

**Comment by lgordey** [comment]
I'm using webpack with RoR backend.

Oh, formatter is rly cool i guess, I'll try it, Thanks!

**Comment by nickjj** [comment]
There's already built in support for rails. Check the api docs:
https://github.com/nickjj/manifest-revision-webpack-plugin#api

Just set `format: 'rails'` and it will output it in a way that works with all the rails helpers.
