### ISSUE TITLE
Blog Link in Readme.md uses an old link

### ISSUE THREAD

**Issue by gerrat** [nickjj/manifest-revision-webpack-plugin#30]
The link to [Flask-Webpack](https://blog.nickjanetakis.com/post/120653461133/manage-your-assets-with-flask-webpack) points to what I'm guessing is your old blog, which uses a certificate only valid for the following domains: *.tumblr.com, tumblr.com.  I'm surmising the link should be updated to point: [here](https://nickjanetakis.com/blog/manage-your-assets-with-flask-webpack).

**Comment by nickjj** [comment]
Gerrat,

Thanks. You're absolutely right and I've updated it.

I used to host my blog on Tumblr but then set up JS redirects for all of my old posts that point to my new site but it seems like Tumblr recently changed things around which cause certificate issues. I'm guessing they recently forced HTTPS.
