### ISSUE TITLE
'ToLocalChecked Empty MaybeLocal' error when running

### ISSUE THREAD

**Issue by ceesvanegmond** [nickjj/manifest-revision-webpack-plugin#35]
Hi!

I'm trying to use this awesome plugin, unfortunately it doesn't work yet.
I added ```new ManifestRevisionPlugin('./resources/assets', {})``` to the plugins in my webpack file, and added ```var ManifestRevisionPlugin = require('manifest-revision-webpack-plugin');``` on top of the file. When trying to run it via Yarn scripts (0.20.3); I get the following error:

```bash
FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::Utils::ReportApiFailure(char const*, char const*) [/usr/local/bin/node]
 4: node::ReadDir(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
 5: 0x4f9c2e63c4f
```

When i comment this plugin out, everything is fine. Any idea how to solve this?

**Comment by nickjj** [comment]
Hi,

Have you tried initializing the plugin with setting the `rootAssetPath` as per the README?
