### ISSUE TITLE
Plugin won't install (Windows 7 x64, WebPack 3.0.0)

### ISSUE THREAD

**Issue by ricosuave73** [nickjj/manifest-revision-webpack-plugin#37]
When installing the plugin via NPM in Windows, the following error occurs:

```
npm WARN saveError ENOENT: no such file or directory, open '[path edited out]\package.json'
[path edited out]
+-- manifest-revision-webpack-plugin@0.4.0
| `-- walk@2.3.9
|   `-- foreachasync@3.0.0
`-- UNMET PEER DEPENDENCY webpack@^1.8.11 || ^2.2.0

npm WARN enoent ENOENT: no such file or directory, open '[path edited out]\package.json'
npm WARN manifest-revision-webpack-plugin@0.4.0 requires a peer of webpack@^1.8.11 || ^2.2.0 but none was installed.
npm WARN master No description
npm WARN master No repository field.
npm WARN master No README data
npm WARN master No license field.
```

It seems the plugin depends on webpack version 1.8.11 - 2.2.0, and currently the default version of webpack is 3.0.0.

**Comment by nickjj** [comment]
Does it install if you configure your `package.json` to use webpack 2.2.0?

**Comment by ricosuave73** [comment]
I don't actually have a package.json (yet). 
What I did was (in this order):

- Install the latest LTS release of Node.js, using the setup from the Node.js site
- Install Flask-Webpack in the virtual environment of my Flask project (pip install Flask-Webpack)
- Install webpack globally using Node.js (npm install webpack -g)
- Install the webpack plugin using (npm install --save manifest-revision-webpack-plugin)

In the last step the error message occurs. 
I understand now that I can write a package.json file to influence the installation of manifest-revision-webpack-plugin?
Please excuse me if this is a moot question, I'm actually in the process of figuring out webpack right now.

**Comment by nickjj** [comment]
My concern is, I haven't tested this plugin yet with webpack 3 yet, so I'm not sure if it'll work out of the box. I thought maybe you had something set up and ready to go. The fix on this library's end might be as simple as just changing the upper version lock to support 3.x.

In your case, for now, I would just make a `package.json` and lock webpack into using 2.2.0. An example one is included in the Flask-Webpack repo at https://github.com/nickjj/flask-webpack/tree/master/flask_webpack/tests/test_app.

If you need to use 3.x's features, you can try making a fork of this library to test it locally.

**Comment by ricosuave73** [comment]
Currently I don't think I need any special Webpack 3 features. If things turn out differently, and I for some reason need to use 3.0, I'll certainly keep you in the loop. But being new to webpack in general, I think I'm better off starting from a stable, working situation, so I think I'll go with using version 2.2.0 for now.
Thanks for your help.
