### ISSUE TITLE
FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal when I want to start my bot with node

### ISSUE THREAD

**Issue by gchabrol** [nickjj/manifest-revision-webpack-plugin#45]
When I want to start my discord bot, I get an error about better sqlite3, I updated this thing and now, when I try to start my bot with "node ." or "node .\index.js" it gives me this

FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.
 1: 00007FF735790205
 2: 00007FF73576A176
 3: 00007FF73576AA50
 4: 00007FF735C7B9A6
 5: 00007FFDD8661A69
 6: 00007FFDD8663170
 7: 00007FFDD866A435
 8: 00007FF73576A7C6
 9: 00007FF735DA4102
10: 00007FF735DA556D
11: 00007FF735DA45F9
12: 00007FF735DA44DB
13: 0000022E056841C1

Then, I uninstall better sqlite 3 and it doesnt change anyhing

Any idea or issues ??

**Comment by nickjj** [comment]
No idea.

Did you open this issue in the wrong repo?

This package isn't associated with discord, sqlite, or v8.

**Comment by gchabrol** [comment]
ho yea sry xD
I'm new in git

**Comment by nickjj** [comment]
No problem. Going to close this one. Good luck!
