### ISSUE TITLE
Generating manifest with subresource integrity?

### ISSUE THREAD

**Issue by mikechau** [nickjj/manifest-revision-webpack-plugin#9]
Any thoughts on generating a rails manifest with a subresource integrity hash?

I was hoping I could just add my own formatter and use your plugin, but it appears the `stats.toJSON()` object is a bit limiting for me.

Currently to get the sri hash, I use [sri-webpack-plugin](https://github.com/mikechau/sri-webpack-plugin), a webpack plugin based on @roman01la's [sri-webpack](https://github.com/roman01la/webpack-sri). In this plugin, it is hooked in to webpack's `this-compilation` (I wish there was more  documentation for this) and then in `optimize-assets`, the source gets hashed and then a object with the filename and sri mapping is injected into `compilation.__CUSTOM_DATA_SRIS`.

I had to modify your plugin a little bit to be able to access the attribute I inject into compilation: https://github.com/mikechau/manifest-revision-webpack-plugin/commit/1c393bcf4a889e4f60f49cdd23c96d7af237e2a1

I made a demo here: https://github.com/mikechau/sri-webpack-demo

I think it would be great if this plugin returned the `compilation` object to the formatter and then you could do whatever you want.

**Comment by mikechau** [comment]
With @IndwiePhoenix's help I was able to find a solution that does not require any changes for this plugin or any need for it to expose `compilation`, I have my subresource integrity plugin instead monkey-patch `stats.toJSON` to include custom stat attributes.

**Comment by IngwiePhoenix** [comment]
And out of nowhere comes a mention.

Glad I could be of good help. :)

**Comment by nickjj** [comment]
@mikechau Glad you found a solution. I was preparing a series of questions to ask you, but it looks like things are good to go on your end.
